[phases.setup]
nixPkgs = ["nodejs_20", "chromium"]

[phases.install]
cmds = ["npm ci"]

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
CHROMIUM_PATH = "/nix/var/nix/profiles/default/bin/chromium"

[start]
cmd = "node src/server.js"
