import { Octokit } from '@octokit/rest';

const GITHUB_API = 'https://github.com/login/oauth';

/**
 * Build GitHub OAuth authorization URL.
 * User visits this URL → approves → GitHub redirects to /api/github/callback
 */
export function getOAuthUrl(state) {
  const params = new URLSearchParams({
    client_id: process.env.GITHUB_CLIENT_ID ?? '',
    scope: 'repo',
    state,
  });
  return `${GITHUB_API}/authorize?${params}`;
}

/**
 * Exchange OAuth code for access token.
 */
export async function exchangeCode(code) {
  const res = await fetch(`${GITHUB_API}/access_token`, {
    method: 'POST',
    headers: { Accept: 'application/json', 'Content-Type': 'application/json' },
    body: JSON.stringify({
      client_id:     process.env.GITHUB_CLIENT_ID,
      client_secret: process.env.GITHUB_CLIENT_SECRET,
      code,
    }),
  });
  if (!res.ok) throw new Error('GitHub token exchange failed');
  const data = await res.json();
  if (data.error) throw new Error(data.error_description ?? data.error);
  return data.access_token;
}

/**
 * Read package.json from a repo and detect the stack.
 * Returns { stack, hasViteSsg, hasSsr }
 */
export async function detectStack(accessToken, owner, repo) {
  const octokit = new Octokit({ auth: accessToken });
  try {
    const { data } = await octokit.repos.getContent({ owner, repo, path: 'package.json' });
    const pkg = JSON.parse(Buffer.from(data.content, 'base64').toString());
    const deps = { ...pkg.dependencies, ...pkg.devDependencies };

    const hasVite    = !!deps.vite;
    const hasNext    = !!deps.next;
    const hasGatsby  = !!deps.gatsby;
    const hasViteSsg = !!deps['vite-ssg'];
    const hasSsr     = !!(deps['@sveltejs/kit'] || deps.nuxt || hasNext);

    const stack = hasNext    ? 'next'
                : hasGatsby  ? 'gatsby'
                : hasVite    ? 'vite'
                : 'static';

    return { stack, hasViteSsg, hasSsr };
  } catch {
    return { stack: 'static', hasViteSsg: false, hasSsr: false };
  }
}

/**
 * Read a file from a repo. Returns { content, sha } or null if not found.
 */
async function getFile(octokit, owner, repo, path) {
  try {
    const { data } = await octokit.repos.getContent({ owner, repo, path });
    return {
      content: Buffer.from(data.content, 'base64').toString(),
      sha: data.sha,
    };
  } catch {
    return null;
  }
}

/**
 * Create or update a file on a branch.
 */
async function putFile(octokit, owner, repo, branch, path, content, message, sha) {
  await octokit.repos.createOrUpdateFileContents({
    owner, repo, path,
    message,
    content: Buffer.from(content).toString('base64'),
    branch,
    ...(sha ? { sha } : {}),
  });
}

/**
 * Create a PR branch with all AI visibility fixes and open the PR.
 * Returns { prUrl }
 */
export async function createFixPR(accessToken, owner, repo, fixes) {
  const octokit    = new Octokit({ auth: accessToken });
  const branch     = 'legibly-ai-fixes';
  const baseBranch = 'main';

  // Get base branch SHA to create fix branch from
  let baseSha;
  try {
    const { data } = await octokit.git.getRef({ owner, repo, ref: `heads/${baseBranch}` });
    baseSha = data.object.sha;
  } catch {
    // Try 'master' if 'main' doesn't exist
    const { data } = await octokit.git.getRef({ owner, repo, ref: 'heads/master' });
    baseSha = data.object.sha;
  }

  // Create or reset the fix branch
  try {
    await octokit.git.createRef({ owner, repo, ref: `refs/heads/${branch}`, sha: baseSha });
  } catch {
    await octokit.git.updateRef({ owner, repo, ref: `heads/${branch}`, sha: baseSha, force: true });
  }

  // Commit each fix file
  const commitMessages = [];
  for (const fix of fixes) {
    const existing = await getFile(octokit, owner, repo, fix.path);
    await putFile(octokit, owner, repo, branch, fix.path, fix.content, fix.message, existing?.sha);
    commitMessages.push(`- ${fix.message}`);
  }

  // Open the PR
  const { data: pr } = await octokit.pulls.create({
    owner, repo,
    title: 'Fix: AI visibility improvements (Legibly)',
    head: branch,
    base: baseBranch,
    body: `## AI Visibility Fixes from Legibly\n\nThis PR applies the fixes identified in your Legibly AI visibility scan.\n\n### Changes made:\n${commitMessages.join('\n')}\n\n### What this fixes:\n- Makes your site readable by AI crawlers (ChatGPT, Claude, Perplexity)\n- Adds structured data so AI knows what your business does\n- Adds llms.txt so AI has a plain-language guide to your site\n- Ensures AI crawlers are allowed in robots.txt\n\n**Merge this PR and your AI visibility score should improve significantly.**\n\n_Generated by [Legibly](https://legibly-production.up.railway.app) — AI Presence Management_`,
  });

  return { prUrl: pr.html_url };
}

/**
 * Parse owner/repo from a GitHub URL.
 * Handles: github.com/owner/repo, https://github.com/owner/repo, owner/repo
 */
export function parseRepo(repoUrl) {
  const cleaned = repoUrl
    .replace(/^https?:\/\/github\.com\//, '')
    .replace(/^github\.com\//, '')
    .replace(/\.git$/, '')
    .trim();
  const parts   = cleaned.split('/').filter(Boolean);
  if (parts.length < 2) throw new Error('Invalid repo URL — use github.com/owner/repo');
  return { owner: parts[0], repo: parts[1] };
}
