import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const archiver = require('archiver');

const PLATFORM_INSTRUCTIONS = {
  wordpress: `## WordPress

1. Install the BlindGEO plugin from wordpress.org/plugins/blindgeo (free)
   OR apply manually:

2. robots.txt — In WordPress admin: Settings → Reading → or use the robots.txt file below.
   Upload robots.txt to your site root (public_html/).

3. llms.txt — Upload llms.txt to your site root (public_html/).

4. schema.json — In WordPress admin, paste the schema snippet into your theme's header.php
   inside <head>, wrapped in: <script type="application/ld+json">...</script>
   OR use a plugin like "Insert Headers and Footers" to add it without editing PHP.`,

  webflow: `## Webflow

1. robots.txt — Go to Site Settings → SEO → Custom Robots.txt. Paste the robots.txt content.

2. llms.txt — Webflow doesn't support arbitrary file hosting natively.
   Upload via Webflow Hosting → Custom Files, or host on a CDN and redirect /llms.txt.
   Alternative: Add the content as a text embed on a hidden page at /llms.

3. schema.json — In Webflow, go to Site Settings → Custom Code → Head Code.
   Paste: <script type="application/ld+json">[paste schema.json content here]</script>`,

  shopify: `## Shopify

1. robots.txt — Shopify controls robots.txt. To customize:
   Online Store → Themes → Edit Code → templates/robots.txt.liquid
   Add the AI crawler rules at the top.

2. llms.txt — Create a new page in Shopify with the handle "llms-txt".
   Add a redirect: /llms.txt → /pages/llms-txt (via Shopify redirects or an app).

3. schema.json — In your theme's theme.liquid, paste the schema inside <head>:
   <script type="application/ld+json">[paste schema.json content here]</script>`,

  squarespace: `## Squarespace

1. robots.txt — Settings → Advanced → External Services → SEO → Custom robots.txt.
   Note: Squarespace on older plans may not support custom robots.txt.

2. llms.txt — Squarespace doesn't support arbitrary file hosting.
   Use a Code Block on a page at /llms to serve the content,
   or use Squarespace Developer mode to add a custom file.

3. schema.json — Settings → Advanced → Code Injection → Header.
   Paste: <script type="application/ld+json">[paste schema.json content here]</script>`,

  default: `## General Instructions

1. robots.txt — Upload to your website root directory (the same folder as index.html).
   If you already have a robots.txt, add the new rules at the top.

2. llms.txt — Upload to your website root directory.
   It should be accessible at yoursite.com/llms.txt

3. schema.json — Copy the contents and paste inside a <script> tag in your page <head>:
   <script type="application/ld+json">
   [paste contents of schema.json here]
   </script>`,
};

function detectPlatform(signals) {
  // Simple heuristic — can be enhanced with platform detection signal
  return 'default';
}

function buildInstructions(domain, platform) {
  const platformInstructions = PLATFORM_INSTRUCTIONS[platform] ?? PLATFORM_INSTRUCTIONS.default;
  return `# BlindGEO Fix Kit — ${domain}

These files will improve your AI visibility score. Apply them to your website
and re-scan at blindgeo.com to confirm your grade improved.

---

${platformInstructions}

---

## What each file does

**robots.txt** — Tells AI crawlers (GPTBot, ClaudeBot, PerplexityBot) that they're
allowed to access your site. Without this file, some AI engines may skip your site.

**llms.txt** — A plain-text summary of your business that AI models read directly.
Without it, AI assistants have to guess what your site is about from scanning individual pages.

**schema.json** — Structured data that tells AI exactly what your business is, what you
offer, and where you're located. AI citation engines rely on this to recommend businesses.

---

After applying all three files, return to blindgeo.com and run a free scan to
confirm your AI visibility grade improved.
`;
}

function buildRobotsTxt() {
  return `User-agent: GPTBot
Allow: /

User-agent: ClaudeBot
Allow: /

User-agent: PerplexityBot
Allow: /

User-agent: Google-Extended
Allow: /

User-agent: Amazonbot
Allow: /

User-agent: *
Allow: /

# Generated by BlindGEO — blindgeo.com
`;
}

export async function generateFixKit({ domain, url, signals, report }) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    const archive = archiver('zip', { zlib: { level: 6 } });

    archive.on('data', chunk => chunks.push(chunk));
    archive.on('end', () => resolve(Buffer.concat(chunks)));
    archive.on('error', reject);

    const platform = detectPlatform(signals);

    // robots.txt
    archive.append(buildRobotsTxt(), { name: 'robots.txt' });

    // llms.txt — use generated content if available, otherwise template
    const llmstxtContent = report?.llmstxt?.content ?? `# ${domain}
> AI-readable guide to ${domain}

## About
${domain} — [your business description]

## Contact
- Site: https://${domain}

# Generated by BlindGEO — blindgeo.com
`;
    archive.append(llmstxtContent, { name: 'llms.txt' });

    // schema.json — use generated recommendations if available
    const schemaRec = report?.schemaRecs?.recommendations?.[0];
    const schemaContent = schemaRec?.snippet
      ?? JSON.stringify({
          '@context': 'https://schema.org',
          '@type': 'Organization',
          'name': domain,
          'url': url ?? `https://${domain}`,
          'description': `${domain} — [describe your business here]`,
        }, null, 2);
    archive.append(schemaContent, { name: 'schema.json' });

    // INSTRUCTIONS.md
    archive.append(buildInstructions(domain, platform), { name: 'INSTRUCTIONS.md' });

    archive.finalize();
  });
}
